// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiPmS3E68Z_pJZ53-rk4NE_m16vba1c-A',
    appId: '1:673708137319:web:84b298bac2fbfe3fe72dc2',
    messagingSenderId: '673708137319',
    projectId: 'carrot-223b9',
    authDomain: 'carrot-223b9.firebaseapp.com',
    storageBucket: 'carrot-223b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3gmr8TcH1Gg8YG9a-cfHWgbwCgolDA4',
    appId: '1:673708137319:android:e7de469d6e2a3f84e72dc2',
    messagingSenderId: '673708137319',
    projectId: 'carrot-223b9',
    storageBucket: 'carrot-223b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTOieHWD1HhXfH3ok3JFmHhVwhaWH2Og',
    appId: '1:673708137319:ios:4ae0f07cfd2d69fde72dc2',
    messagingSenderId: '673708137319',
    projectId: 'carrot-223b9',
    storageBucket: 'carrot-223b9.appspot.com',
    iosClientId: '673708137319-prfeq0md0pa9hbt6tehbc352e148hoko.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCTOieHWD1HhXfH3ok3JFmHhVwhaWH2Og',
    appId: '1:673708137319:ios:4ae0f07cfd2d69fde72dc2',
    messagingSenderId: '673708137319',
    projectId: 'carrot-223b9',
    storageBucket: 'carrot-223b9.appspot.com',
    iosClientId: '673708137319-prfeq0md0pa9hbt6tehbc352e148hoko.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotApp',
  );
}
